kind: environment
environment_name: ArgoCD Multi DBS env
state: active
owner_email: david.b@quali.com
blueprint:
  name: argocd-multi-sveta
  repository_name: test-spec2-public
  commit: e6192bb8a5976bd898f7f84870e0401672c2f933
inputs:
  application_name1: sveta-s3-upbound
  application_name2: sveta-nginx-deployment
  project: default
  agent_name: eks-sveta
tags: {}
grains: {}
