apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
#  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
#    app: {{ template "deployment.name" . }}
#    chart: {{ template "deployment.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
