apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sveta-nginx-app
spec:
  project: default
  source:
    repoURL: "https://github.com/QualiNext/test-spec2-public.git"
    path: argocd/nginx
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sveta-test